//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTPayExtension
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allowance
    {
        public Allowance()
        {
            this.DutyAllowanceMappings = new HashSet<DutyAllowanceMapping>();
            this.PremiumClients = new HashSet<PremiumClient>();
            this.ContractorAddons = new HashSet<ContractorAddon>();
        }
    
        public int AllowanceId { get; set; }
        public string AllowanceDescription { get; set; }
        public decimal AllowanceRate { get; set; }
        public decimal CalculateOnMaxHours { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string PayrollCode { get; set; }
        public string LastModifiedBy { get; set; }
    
        public virtual ICollection<DutyAllowanceMapping> DutyAllowanceMappings { get; set; }
        public virtual ICollection<PremiumClient> PremiumClients { get; set; }
        public virtual ICollection<ContractorAddon> ContractorAddons { get; set; }
    }
}
