//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTPayExtension
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerZoneView
    {
        public int ZoneId { get; set; }
        public string ZoneDescription { get; set; }
        public int CustomerId { get; set; }
        public bool Active { get; set; }
    }
}
