//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTPayExtension
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerView
    {
        public CustomerView()
        {
            this.PremiumClients = new HashSet<PremiumClient>();
            this.ContractorAddons = new HashSet<ContractorAddon>();
        }
    
        public int CustomerId { get; set; }
        public string CustomerRef { get; set; }
        public string CustomerDescription { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public string ZoneDescription { get; set; }
    
        public virtual ZoneMapping ZoneMapping { get; set; }
        public virtual ICollection<PremiumClient> PremiumClients { get; set; }
        public virtual ICollection<ContractorAddon> ContractorAddons { get; set; }
        public virtual CustomerSpecificRate CustomerSpecificRate { get; set; }
    }
}
