//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTPayExtension
{
    using System;
    using System.Collections.Generic;
    
    public partial class DutyCodeView
    {
        public DutyCodeView()
        {
            this.DutyAllowanceMappings = new HashSet<DutyAllowanceMapping>();
            this.PremiumClients = new HashSet<PremiumClient>();
            this.ContractorAddons = new HashSet<ContractorAddon>();
        }
    
        public int DutyId { get; set; }
        public string DutyCode { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public double Rate { get; set; }
        public string Code { get; set; }
        public string PayrollCodeDescription { get; set; }
    
        public virtual ICollection<DutyAllowanceMapping> DutyAllowanceMappings { get; set; }
        public virtual ICollection<PremiumClient> PremiumClients { get; set; }
        public virtual ICollection<ContractorAddon> ContractorAddons { get; set; }
    }
}
