//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTPayExtension
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeOwnWeapon
    {
        public int EmployeeOwnWeaponId { get; set; }
        public int ContractorId { get; set; }
        public string FirearmDescription { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<System.DateTime> PermitExpiration { get; set; }
        public System.DateTime LastmodifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public int AllowanceId { get; set; }
    
        public virtual ContractorView ContractorView { get; set; }
    }
}
