//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTPayExtension
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportedTransaction
    {
        public int ExportedTransId { get; set; }
        public int ImportedTransId { get; set; }
        public System.DateTime DateExported { get; set; }
        public decimal Rate { get; set; }
        public decimal Quantity { get; set; }
        public int AllowanceId { get; set; }
        public bool IsAllowance { get; set; }
        public string ExportedBy { get; set; }
    }
}
