//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTPayExtension
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportedTransactionSummary
    {
        public string ServiceCode { get; set; }
        public Nullable<decimal> ShiftTotal { get; set; }
        public int CustomerId { get; set; }
        public int ContractorId { get; set; }
        public string ContractorFirstName { get; set; }
        public string ContractorLastName { get; set; }
        public string ContractorDescription { get; set; }
        public string CustomerDescription { get; set; }
        public decimal DutyRate { get; set; }
        public string AllowanceDescription { get; set; }
        public string ContractorRef { get; set; }
        public string DutyDescription { get; set; }
        public string PayrollCode { get; set; }
        public int ReferenceId { get; set; }
        public bool IsAllowance { get; set; }
        public Nullable<System.DateTime> DateExported { get; set; }
        public int BatchNo { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string FileSaveName { get; set; }
        public string LocationImportedFrom { get; set; }
        public int CompanyId { get; set; }
        public string ImportedBy { get; set; }
        public string ExportedBy { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
