//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTPayExtension
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuardMappingView
    {
        public int ContractorId { get; set; }
        public int GuardTypeId { get; set; }
        public string GuardTypeDescription { get; set; }
        public decimal Rate { get; set; }
        public string ContractorRef { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ContractorDescription { get; set; }
        public bool Allowance { get; set; }
        public short CompanyId { get; set; }
    }
}
