//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTPayExtension
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuardForceDisplayView
    {
        public int ContractorId { get; set; }
        public string ContractorRef { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ContractorDescription { get; set; }
        public short CompanyId { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string TRN { get; set; }
        public string NISNo { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string TitleOfCourtesy { get; set; }
        public decimal Rate { get; set; }
        public string GuardTypeDescription { get; set; }
    }
}
