//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTPayExtension
{
    using System;
    using System.Collections.Generic;
    
    public partial class HolidayRate
    {
        public HolidayRate()
        {
            this.Holidays = new HashSet<Holiday>();
        }
    
        public int HolidayRateId { get; set; }
        public string Description { get; set; }
        public decimal RateMultiplier { get; set; }
        public System.DateTime LastModiedDate { get; set; }
        public bool Active { get; set; }
        public string LastModifiedBy { get; set; }
    
        public virtual ICollection<Holiday> Holidays { get; set; }
    }
}
