//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTPayExtension
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportedTransactionsView
    {
        public int ImportedTransId { get; set; }
        public string TransactionDate { get; set; }
        public int CustomerId { get; set; }
        public int ContractorId { get; set; }
        public string ServiceCode { get; set; }
        public decimal ShiftTotal { get; set; }
        public int BatchNo { get; set; }
        public System.DateTime DateImported { get; set; }
        public string LocationImportedFrom { get; set; }
        public string FileSaveName { get; set; }
        public int IsExported { get; set; }
        public Nullable<System.DateTime> ConvertedImportDate { get; set; }
        public string ContractorDescription { get; set; }
        public string GuardTypeDescription { get; set; }
        public string CustomerDescription { get; set; }
        public string ZoneDescription { get; set; }
        public string Description { get; set; }
    }
}
