//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTPayExtension
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportCaluclationSummaryView
    {
        public string ContractorRef { get; set; }
        public string PayrollCode { get; set; }
        public string ServiceCode { get; set; }
        public Nullable<decimal> DutyRate { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string GLAccount { get; set; }
        public string Location { get; set; }
        public string Branch { get; set; }
        public string Department { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string ContractorDescription { get; set; }
        public int ReferenceId { get; set; }
        public Nullable<bool> IsAllowance { get; set; }
    }
}
