//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTPayExtension
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollCodeView
    {
        public short PayrollCodeId { get; set; }
        public short CompanyId { get; set; }
        public string CategoryId { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string ShortDescription { get; set; }
        public bool PrivateToCompany { get; set; }
        public bool DeductNisBeforeCalculatingPen { get; set; }
        public bool GovernmentApproved { get; set; }
        public bool OvertimeCode { get; set; }
        public string EmployeeGL { get; set; }
        public bool UseFormattingConventionForEmployeeGL { get; set; }
        public string EmployerGL { get; set; }
        public bool UseFormattingConventionForEmployerGL { get; set; }
        public string VolGL { get; set; }
        public bool UseFormattingConventionForVolGL { get; set; }
        public float EmployeeDefault { get; set; }
        public float EmployerDefault { get; set; }
        public float VoluntaryDefault { get; set; }
        public bool SystemCode { get; set; }
        public bool Active { get; set; }
        public string VisualSmartCode { get; set; }
        public short BeneficiaryId { get; set; }
        public byte Priority { get; set; }
        public bool DisallowVoluntaryDeduction { get; set; }
        public string Reference { get; set; }
        public bool RetroCode { get; set; }
        public bool ArrearsCode { get; set; }
        public string PayrollCode { get; set; }
    }
}
