//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTPayExtension
{
    using System;
    using System.Collections.Generic;
    
    public partial class PremiumClient
    {
        public int PremiumClientId { get; set; }
        public int CustomerId { get; set; }
        public int DutyId { get; set; }
        public int AllowanceId { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public decimal AllowanceRate { get; set; }
        public decimal CalculateOnMaxHours { get; set; }
        public string LastModifiedBy { get; set; }
    
        public virtual Allowance Allowance { get; set; }
        public virtual DutyCodeView DutyCodeView { get; set; }
        public virtual CustomerView CustomerView { get; set; }
    }
}
