//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTPayExtension
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMARTPayCompanyView
    {
        public short CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string Description { get; set; }
        public string TradeName { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string NISNo { get; set; }
        public string TaxRef { get; set; }
        public string TRN { get; set; }
        public string FrequencyId { get; set; }
        public short NoOfPeriodsInYear { get; set; }
        public short CurrentPeriod { get; set; }
        public string CurrentYear { get; set; }
        public System.DateTime CurrentPeriodEndingDate { get; set; }
        public System.DateTime CurrentNisEndingDate { get; set; }
        public string TypeOfTaxCredit { get; set; }
        public decimal AnnualTaxCredit { get; set; }
        public string GLFormat { get; set; }
        public string PayrollType { get; set; }
        public float TaxablePortionOfPay { get; set; }
        public string PayAdviceFormat { get; set; }
        public string ChequeFormat { get; set; }
        public int TaxSchemeId { get; set; }
        public int DefaultRentalCode { get; set; }
        public float Addon { get; set; }
        public string CurrencyId { get; set; }
        public decimal NisCeiling { get; set; }
        public string WageType { get; set; }
        public float RegularHours { get; set; }
        public string PaymentType { get; set; }
        public string DeductionExcessOption { get; set; }
        public bool SupressDisplayOfRental { get; set; }
        public string PayrollClearingAccount { get; set; }
        public bool UseFormattingConvention { get; set; }
        public string PayrollSuspenseAccount { get; set; }
        public string ProcessingStatus { get; set; }
        public string DefaultBackupPath { get; set; }
        public string PayrollAc { get; set; }
        public short BankId { get; set; }
        public short BankBranchId { get; set; }
        public string IndentificationNo { get; set; }
        public string ETransExportPath { get; set; }
        public string GLExportType { get; set; }
        public string GLExportPath { get; set; }
        public bool Consolidate { get; set; }
        public byte[] Logo { get; set; }
        public string ProbationaryPeriod { get; set; }
        public bool AutoUpdateEmpType { get; set; }
        public string FrequencyDescription { get; set; }
        public bool DualTaxfree { get; set; }
        public byte StartPeriod { get; set; }
        public decimal PrimaryTaxfree { get; set; }
        public decimal SecondaryTaxfree { get; set; }
        public bool AutoCalculate { get; set; }
        public short CountryId { get; set; }
        public bool GraduatedIncomeTax { get; set; }
        public bool PrintCompanyNameOnPayAdvice { get; set; }
        public string EmailAddress { get; set; }
        public string PhoneNo { get; set; }
        public string MailingAddressLine1 { get; set; }
        public string MailingAddressLine2 { get; set; }
        public bool OverTimeDays { get; set; }
        public bool OverTimePeriod { get; set; }
        public double OverTimeAmount { get; set; }
        public bool ClockIncluded { get; set; }
        public string ClockVersion { get; set; }
        public bool AutoApproval { get; set; }
        public short OverTimeReasonId { get; set; }
        public string OverTimeReason { get; set; }
        public System.DateTime LastModified { get; set; }
        public string LastModifiedBy { get; set; }
        public decimal MaxPensionPercentage { get; set; }
    }
}
