//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTPayExtension
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class SMARTPayExtensionEntities : DbContext
    {
        public SMARTPayExtensionEntities()
            : base("name=SMARTPayExtensionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Allowance> Allowances { get; set; }
        public DbSet<GuardType> GuardTypes { get; set; }
        public DbSet<Holiday> Holidays { get; set; }
        public DbSet<HolidayRate> HolidayRates { get; set; }
        public DbSet<ZoneMapping> ZoneMappings { get; set; }
        public DbSet<Zone> Zones { get; set; }
        public DbSet<ContractorView> ContractorViews { get; set; }
        public DbSet<DutyCodeView> DutyCodeViews { get; set; }
        public DbSet<ImportedTransaction> ImportedTransactions { get; set; }
        public DbSet<SysNumberSequence> SysNumberSequences { get; set; }
        public DbSet<ImportedTransactionsView> ImportedTransactionsViews { get; set; }
        public DbSet<DutyAllowanceMapping> DutyAllowanceMappings { get; set; }
        public DbSet<CustomerView> CustomerViews { get; set; }
        public DbSet<GuardStatusMapping> GuardStatusMappings { get; set; }
        public DbSet<PremiumClient> PremiumClients { get; set; }
        public DbSet<ContractorAddon> ContractorAddons { get; set; }
        public DbSet<EmployeeOwnWeapon> EmployeeOwnWeapons { get; set; }
        public DbSet<SystemUser> SystemUsers { get; set; }
        public DbSet<ImportCalcuationDetailsView> ImportCalcuationDetailsViews { get; set; }
        public DbSet<SystemMenuView> SystemMenuViews { get; set; }
        public DbSet<MenuOption> MenuOptions { get; set; }
        public DbSet<SystemUserAccess> SystemUserAccesses { get; set; }
        public DbSet<SystemUserView> SystemUserViews { get; set; }
        public DbSet<SMARTPayCompanyView> SMARTPayCompanyViews { get; set; }
        public DbSet<GuardForceDisplayView> GuardForceDisplayViews { get; set; }
        public DbSet<ExportedTransactionDetail> ExportedTransactionDetails { get; set; }
        public DbSet<PayrollCodeView> PayrollCodeViews { get; set; }
        public DbSet<ImportCaluclationSummaryView> ImportCaluclationSummaryViews { get; set; }
        public DbSet<ExportedTransaction> ExportedTransactions { get; set; }
        public DbSet<ExportedTransactionSummary> ExportedTransactionSummaries { get; set; }
        public DbSet<SystemUserSetting> SystemUserSettings { get; set; }
        public DbSet<CustomerSpecificRate> CustomerSpecificRates { get; set; }
        public DbSet<CustomerZoneView> CustomerZoneViews { get; set; }
        public DbSet<CostAnalysisView> CostAnalysisViews { get; set; }
        public DbSet<TimeAnalysisView> TimeAnalysisViews { get; set; }
        public DbSet<ServiceAnalysisView> ServiceAnalysisViews { get; set; }
        public DbSet<GuardMappingView> GuardMappingViews { get; set; }
        public DbSet<GuardLocationPayrollUpdate> GuardLocationPayrollUpdates { get; set; }
        public DbSet<ImportedTransactionsLocationView> ImportedTransactionsLocationViews { get; set; }
    
        public virtual int UpdateGuardLocation()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateGuardLocation");
        }
    }
}
