//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTPayExtension
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemMenuView
    {
        public int MenuNodesId { get; set; }
        public int MenuId { get; set; }
        public string NodeDescription { get; set; }
        public string NodeControlName { get; set; }
        public string MenuDescription { get; set; }
        public string MenuControlName { get; set; }
    }
}
