//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTPayExtension
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeAnalysisView
    {
        public string CostComponent { get; set; }
        public System.DateTime DateExported { get; set; }
        public decimal Hours { get; set; }
        public string ExportedBy { get; set; }
    }
}
